import { Container } from '@mantine/core';

const Page = () => {
  return (
    <Container className="bg-black text-white p-8 md:p-12 lg:p-16 rounded-lg shadow-lg max-w-4xl mx-auto">
      <h1 className="mb-6 text-center text-3xl font-bold md:text-4xl lg:text-5xl">
        <a id="features"></a> Privacy Policy and Terms of Service
      </h1>

      <div className="mb-6">
        <a className="text-2xl mb-2 text-blue-400 hover:underline" id="License" href="/terms/#License">
          What license do my analytics have?
        </a>
        <p className="text-lg mb-4">
          All the analytics that are generated in Ved are owned by you. You decide which license applies to the
          analytics generated. We assure you that we do NOT intend to collect any metrics from your website&apos;s data.
        </p>
      </div>

      <div className="mb-6">
        <a
          className="text-2xl mb-2 text-blue-400 hover:underline"
          id="YourPublicInformation"
          href="/terms/#YourPublicInformation"
        >
          Your Public Information
        </a>
        <p className="text-lg mb-4">
          Ved Analytics is a public platform. Anyone from anywhere can create a Ved account and use it to generate
          analytics. However, data generated by that user can only be accessed by that user.
        </p>
      </div>

      <div className="mb-6">
        <a
          className="text-2xl mb-2 text-blue-400 hover:underline"
          id="YourPrivateInformation"
          href="/terms/#YourPrivateInformation"
        >
          Your Private Information
        </a>
        <p className="text-lg mb-4">
          Ved respects the privacy of its users and will not use data in its databases to compete with its users, market
          to its user&apos;s clients, or contact them for any other means of profit.
        </p>
        <p className="text-lg mb-4">
          Ved collects usernames ONLY. It uses only GitHub for authentication and stores the username of its users. Ved
          does NOT store any passwords in our database in any form.
        </p>
        <p className="text-lg mb-4">
          All private information, including usernames and analytics, is never shared with or sold to any other
          organizations or services. Only you have the right to share your analytics with others.
        </p>
      </div>

      <div className="mb-6">
        <a className="text-2xl mb-2 text-blue-400 hover:underline" id="Cookies" href="/terms/#Cookies">
          Cookies and Analytics
        </a>
        <p className="text-lg mb-4">
          Cookies are required to use Ved. They help the system identify users and maintain their session while working
          on the website.
        </p>
      </div>

      <div className="mb-6">
        <a className="text-2xl mb-2 text-blue-400 hover:underline" id="Refunds" href="/terms/#Refunds">
          Refunds and Cancellation
        </a>
        <p className="text-lg mb-4">
          Ved users have full right to cancel their subscriptions any time. We won&apos;t put any unfair practices to
          prevent users from cancelling their subscriptions. However, due to technical challenges, we won&apos;t be able
          to provide refunds for the period you have purchased the product for. If you feel like Ved is not for you, you
          have the full right to cancel the subscription for the next period.
        </p>
      </div>

      <div className="mb-6">
        <a className="text-2xl mb-2 text-blue-400 hover:underline" id="Terminating" href="/terms/#Terminating">
          Terminating your Account
        </a>
        <p className="text-lg mb-4">
          If you decide to delete your Ved account, all the analytics you created and your profile will be deleted. Ved
          runs cleanup scripts when you request deletion.
        </p>
      </div>

      <div className="mb-6">
        <a className="text-2xl mb-2 text-blue-400 hover:underline" id="Changes" href="/terms/#Changes">
          Changes to This Policy
        </a>
        <p className="text-lg mb-4">
          Ved&apos;s Privacy Policy may change from time to time. Ved will not reduce its user&apos;s rights under this
          policy without explicit consent.
        </p>
      </div>

      <div className="mb-6">
        <a className="text-2xl mb-2 text-blue-400 hover:underline" id="Terms" href="/terms/#Terms">
          Terms of Service
        </a>
        <p className="text-lg mb-4">
          You must be at least 13 years old to use Ved. Ved reserves the right to suspend any user account and block any
          websites and analytics without further notice.
        </p>
      </div>

      <div className="mb-6">
        <a className="text-2xl mb-2 text-blue-400 hover:underline" id="Uses" href="/terms/#Uses">
          Ved Uses
        </a>
        <ul className="text-lg list-disc list-inside">
          <li className="mb-2">
            <a href="https://nextjs.org/" className="text-blue-500 hover:underline">
              Next.js
            </a>{' '}
            - for the website framework.
          </li>
          <li className="mb-2">
            <a href="https://ui.shadcn.com" className="text-blue-500 hover:underline">
              ShadCN
            </a>{' '}
            - for the UI components.
          </li>
          <li className="mb-2">
            <a href="https://github.com/" className="text-blue-500 hover:underline">
              GitHub
            </a>{' '}
            - for authentication and storing proprietary code.
          </li>
          <li className="mb-2">
            <a href="https://aws.amazon.com/" className="text-blue-500 hover:underline">
              AWS
            </a>{' '}
            - for deploying our services.
          </li>
          <li className="mb-2">
            <a href="https://razorpay.com/" className="text-blue-500 hover:underline">
              Razorpay
            </a>{' '}
            - for handling payments and subscriptions.
          </li>
        </ul>
      </div>
      <div className="mb-10">
  <a
    className="text-3xl mb-4 text-blue-500 hover:text-blue-300 hover:underline transition-all duration-200 ease-in-out"
    id="Contact"
    href="/terms/#Contact"
  >
    Contact
  </a>
  <p className="text-lg mb-6 text-gray-300 leading-relaxed">
    If you have further queries, feel free to reach out via the following:
  </p>
  <ul className="space-y-2 text-gray-200">
    <li>
      <strong className="text-white">Email:</strong>{' '}
      <a
        href="mailto:shubhdoesnotexists@gmail.com"
        className="hover:text-blue-300 transition-all duration-200 ease-in-out"
      >
        shubhdoesnotexists@gmail.com
      </a>
    </li>
    <li>
      <strong className="text-white">Twitter:</strong>{' '}
      <a
        href="https://x.com/shubh_exists"
        className="hover:text-blue-300 transition-all duration-200 ease-in-out"
        target="_blank"
        rel="noopener noreferrer"
      >
        @shubh_exists
      </a>
    </li>
    <li>
      <strong className="text-white">WhatsApp:</strong>{' '}
      <span className="hover:text-blue-300 transition-all duration-200 ease-in-out">
        +91 9354992488
      </span>
    </li>
    <li>
      <strong className="text-white">Operational Address :</strong>{' '}
      <span className="hover:text-blue-300 transition-all duration-200 ease-in-out">
        Preet Vihar, Delhi - 110092, India
      </span>
    </li>
  </ul>
</div>

    </Container>
  );
};

export default Page;
